#ifndef DEFINES_GLSL
#define DEFINES_GLSL

// Vertex attribute locations
#define VERTEX_POSITION_LOCATION 0
#define VERTEX_UV_LOCATION 1
#define VERTEX_NORMAL_LOCATION 2
#define VERTEX_TANGENT_LOCATION 3
#define VERTEX_BITANGENT_LOCATION 4

// Uniform bindings
#define BUFFER_CAMERA_BINDING 0
#define BUFFER_MATRICES_BINDING 1
#define BUFFER_MATERIAL_BINDING 2

#endif // DEFINES_GLSL
