#ifndef LOCATIONS_GLSL
#define LOCATIONS_GLSL

// Vertex attributes locations
#define VERTEX_POSITION_LOCATION 0
#define VERTEX_UV_LOCATION 1
#define VERTEX_NORMAL_LOCATION 2
#define VERTEX_TANGENT_LOCATION 3
#define VERTEX_BITANGENT_LOCATION 4

#endif // LOCATIONS_GLSL
